### ISSUE TITLE
cant register on your forum

### ISSUE THREAD

**Issue by raykai** [bbDKP/PBWoW3style#18]
can't register on your forum after pressing submit i get a SQL error
![bug](https://user-images.githubusercontent.com/8138894/44549890-952e4700-a6f0-11e8-8e7a-e07e72215757.JPG)

**Comment by raykai** [comment]
so i came here to find the pbWow Heroes 3.2 but can't find it.

**Comment by avandenberghe** [comment]
hello, 

that error is now fixed. 

in order to download please use link https://www.avathar.be/bbdkp/app.php/dlext/?view=detail&df_id=52 <https://www.avathar.be/bbdkp/app.php/dlext/?view=detail&df_id=52>
