### ISSUE TITLE
navbar.html has a work line in it and causing double breadcrumb navilinks after Forum Home.

### ISSUE THREAD

**Issue by Amasov** [bbDKP/PBWoW3style#21]
This shouldn't be there:

Branch Develop32/Master32
PBWoW3style/styles/pbwow3/template/navbar.htm Line 16:

`<span class="crumb" {$MICRODATA}<!-- IF navlinks.MICRODATA --> {navlinks.MICRODATA}<!-- ENDIF -->><a href="{navlinks.U_VIEW_FORUM}" itemprop="url"><span itemprop="title">{navlinks.FORUM_NAME}</span></a></span>`

This line causing double breadcrumb navilinks

Pictures:
http://i.imgur.com/F1Yjkqo.jpg
http://i.imgur.com/YGnQTYP.jpg

BR,
Chris

**Comment by avandenberghe** [comment]
thank you for the bug report, this is now fixed.
