### ISSUE TITLE
Post text is under the avatar area

### ISSUE THREAD

**Issue by Athris** [bbDKP/PBWoW3style#24]
With the last phpBB and PBWoW Style update the post text is under the avatar area:
![grafik](https://user-images.githubusercontent.com/11237138/96235834-8cb5bc00-0f9b-11eb-9cc8-a2790d3f3687.png)

Using:
pbpBB: 3.3.1
PBWoW Style: 3.3.0
PBWoW Extension: 3.2.8

I use a unmodified PBWow style version for testing.

**Comment by avandenberghe** [comment]
please see a hotfix here 
http://www.avathar.be/forum/viewtopic.php?p=17126&#p17126
a new release for phpbb 3.3.1 is underway

**Comment by avandenberghe** [comment]
fixed in pbwow 3.3.1
