### ISSUE TITLE
add 3.2 substyles

### ISSUE THREAD

**Issue by avandenberghe** [bbDKP/PBWoW3style#8]
- pbwow3_battlecry 	
- pbwow3_diablo 	
- pbwow3_garrison 	
- pbwow3_heroes 	
- pbwow3_pandaria 	
- pbwow3_tbc 	
- pbwow3_tech 	
- pbwow3_tribute 	
- pbwow3_warlords 	
- pbwow3_wildstar 	
- pbwow3_wotlk 	
- pbwow3_xmas
- pbwow3_legion

**Comment by Galixte** [comment]
@Sajaki, what about Legion?

**Comment by Galixte** [comment]
So?

**Comment by avandenberghe** [comment]
of course these will be done, but it's not really an issue to be tracked here.
